
package slide.exemplo.caneta;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Danielen Santana
 * @since 04/10/2023
 * @details Criação da frmCaneta a partir do exemplo demonstrado no slide
 * @note Exemplo criado no curso de Programação Orientada a Objeto 
 * ministrada pelo professor Dr.Fabio Marques.
 */
public class frmCaneta extends javax.swing.JFrame {

    Caneta caneta = new Caneta();
    ArrayList<Caneta> canetas = new ArrayList(); // Criação de uma array para salvar as canetas.
    
    DefaultTableModel modelo;
  
    public frmCaneta() {
        initComponents();
        tbCaneta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION); // Seleciona somente uma linha
        
        modelo = (DefaultTableModel) tbCaneta.getModel(); // Pega a tabela e passa para variavel modelo
        modelo.addColumn("Modelo");
        modelo.addColumn("Ponta");
        modelo.addColumn("Cor");
        modelo.addColumn("Carga");
        modelo.addColumn("Estado");
        txtModelo.setBorder(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton3 = new javax.swing.JRadioButton();
        Pontas = new javax.swing.ButtonGroup();
        Cores = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtModelo = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        rbVermelha = new javax.swing.JRadioButton();
        rbAzul = new javax.swing.JRadioButton();
        rbPreta = new javax.swing.JRadioButton();
        rbVerde = new javax.swing.JRadioButton();
        jPanel10 = new javax.swing.JPanel();
        rb14 = new javax.swing.JRadioButton();
        rb10 = new javax.swing.JRadioButton();
        rb07 = new javax.swing.JRadioButton();
        rb16 = new javax.swing.JRadioButton();
        cadastrarButtom = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        destampar = new javax.swing.JButton();
        tampar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jSlider1 = new javax.swing.JSlider();
        nivelCarga = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCaneta = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();

        jRadioButton3.setBackground(new java.awt.Color(255, 204, 204));
        jRadioButton3.setText("Azul");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Canetas");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 153, 153));
        setForeground(new java.awt.Color(255, 102, 153));

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Modelo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(18, 27, 56))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(37, 37, 37));
        jPanel1.setName(""); // NOI18N

        txtModelo.setBackground(new java.awt.Color(255, 204, 204));
        txtModelo.setForeground(new java.awt.Color(24, 43, 69));
        txtModelo.setAlignmentX(0.25F);
        txtModelo.setAlignmentY(0.25F);
        txtModelo.setCaretColor(new java.awt.Color(24, 43, 69));
        txtModelo.setDisabledTextColor(new java.awt.Color(24, 43, 69));
        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtModelo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtModelo)
                .addGap(5, 5, 5))
        );

        jPanel7.setBackground(new java.awt.Color(255, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Cor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(18, 27, 56))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(37, 37, 37));
        jPanel7.setName(""); // NOI18N

        rbVermelha.setBackground(new java.awt.Color(255, 204, 204));
        Cores.add(rbVermelha);
        rbVermelha.setForeground(new java.awt.Color(37, 37, 37));
        rbVermelha.setText("Vermelha");
        rbVermelha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVermelhaActionPerformed(evt);
            }
        });

        rbAzul.setBackground(new java.awt.Color(255, 204, 204));
        Cores.add(rbAzul);
        rbAzul.setForeground(new java.awt.Color(37, 37, 37));
        rbAzul.setText("Azul");

        rbPreta.setBackground(new java.awt.Color(255, 204, 204));
        Cores.add(rbPreta);
        rbPreta.setForeground(new java.awt.Color(37, 37, 37));
        rbPreta.setText("Preta");

        rbVerde.setBackground(new java.awt.Color(255, 204, 204));
        Cores.add(rbVerde);
        rbVerde.setForeground(new java.awt.Color(37, 37, 37));
        rbVerde.setText("Verde");
        rbVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbVerdeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbVermelha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbPreta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbVerde)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rbVerde)
                    .addComponent(rbPreta)
                    .addComponent(rbVermelha)
                    .addComponent(rbAzul))
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Ponta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(18, 27, 56))); // NOI18N
        jPanel10.setForeground(new java.awt.Color(37, 37, 37));
        jPanel10.setName(""); // NOI18N

        rb14.setBackground(new java.awt.Color(255, 204, 204));
        Pontas.add(rb14);
        rb14.setText("1.4");

        rb10.setBackground(new java.awt.Color(255, 204, 204));
        Pontas.add(rb10);
        rb10.setText("1.0");
        rb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb10ActionPerformed(evt);
            }
        });

        rb07.setBackground(new java.awt.Color(255, 204, 204));
        Pontas.add(rb07);
        rb07.setForeground(new java.awt.Color(37, 37, 37));
        rb07.setText("0.7");
        rb07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb07ActionPerformed(evt);
            }
        });

        rb16.setBackground(new java.awt.Color(255, 204, 204));
        Pontas.add(rb16);
        rb16.setText("1.6");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb07)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rb16)
                    .addComponent(rb14)
                    .addComponent(rb10)
                    .addComponent(rb07))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cadastrarButtom.setBackground(new java.awt.Color(255, 102, 153));
        cadastrarButtom.setForeground(new java.awt.Color(37, 37, 37));
        cadastrarButtom.setText("Cadastrar");
        cadastrarButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarButtomActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(255, 102, 153));
        btnEditar.setForeground(new java.awt.Color(37, 37, 37));
        btnEditar.setText("Editar");
        btnEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditarMouseClicked(evt);
            }
        });
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        destampar.setBackground(new java.awt.Color(255, 102, 153));
        destampar.setForeground(new java.awt.Color(37, 37, 37));
        destampar.setText("Destampar");
        destampar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destamparActionPerformed(evt);
            }
        });

        tampar.setBackground(new java.awt.Color(255, 102, 153));
        tampar.setForeground(new java.awt.Color(37, 37, 37));
        tampar.setText("Tampar");
        tampar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamparActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 102, 153));
        jButton5.setForeground(new java.awt.Color(37, 37, 37));
        jButton5.setText("Sair");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jPanel12.setBackground(new java.awt.Color(255, 204, 204));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Carga", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(18, 27, 56))); // NOI18N
        jPanel12.setName(""); // NOI18N

        jSlider1.setBackground(new java.awt.Color(255, 204, 204));
        jSlider1.setForeground(new java.awt.Color(240, 100, 178));
        jSlider1.setPaintLabels(true);
        jSlider1.setPaintTicks(true);
        jSlider1.setToolTipText("");
        jSlider1.setValue(0);
        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });

        nivelCarga.setForeground(new java.awt.Color(37, 37, 37));
        nivelCarga.setText("0");

        jLabel1.setForeground(new java.awt.Color(37, 37, 37));
        jLabel1.setText("%");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(jSlider1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nivelCarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSlider1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nivelCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );

        tbCaneta.setForeground(new java.awt.Color(37, 37, 37));
        tbCaneta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbCaneta.setToolTipText("");
        tbCaneta.setGridColor(new java.awt.Color(250, 190, 190));
        tbCaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbCanetaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCaneta);

        jScrollPane2.setViewportView(jScrollPane1);

        jButton3.setBackground(new java.awt.Color(255, 102, 153));
        jButton3.setForeground(new java.awt.Color(37, 37, 37));
        jButton3.setText("Exibir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 102, 153));
        jButton4.setForeground(new java.awt.Color(37, 37, 37));
        jButton4.setText("Remover");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cadastrarButtom)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(destampar)
                                .addGap(20, 20, 20)
                                .addComponent(tampar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEditar, cadastrarButtom, destampar, jButton3, jButton4, jButton5, tampar});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastrarButtom)
                    .addComponent(destampar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5)
                    .addComponent(tampar)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEditar, cadastrarButtom, destampar, jButton5, tampar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void cadastrarButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarButtomActionPerformed
        caneta.modelo = txtModelo.getText();
        if ( rbAzul.isSelected())
        {
            caneta.cor = rbAzul.getText();
        } else if (rbVermelha.isSelected()) {
            caneta.cor = rbVermelha.getText();
        } else if ( rbPreta.isSelected()) {
            caneta.cor = rbPreta.getText();
        } else {
            caneta.cor = rbVerde.getText();
        }
        
        if (rb07.isSelected())
        {
            caneta.ponta = Float.parseFloat(rb07.getText());
        } else if (rb10.isSelected()) {
            caneta.ponta = Float.parseFloat(rb10.getText());
        } else if (rb14.isSelected()) {
            caneta.ponta = Float.parseFloat(rb14.getText());
        } else {
            caneta.ponta = Float.parseFloat(rb16.getText());
        }
        
        caneta.carga = Integer.parseInt(nivelCarga.getText());
        
        canetas.add(caneta);
        
        modelo.addRow(new Object [] {caneta.modelo, caneta.ponta, caneta.cor, caneta.carga, caneta.tampada});
        
        caneta = new Caneta();
    }//GEN-LAST:event_cadastrarButtomActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    
        modelo.setValueAt(txtModelo.getText(),tbCaneta.getSelectedRow(), 0);
        
        if (rb07.isSelected()) {
            modelo.setValueAt(Float.parseFloat(rb07.getText()), tbCaneta.getSelectedRow(), 1);
        } else if (rb10.isSelected()) {
            modelo.setValueAt(Float.parseFloat(rb10.getText()), tbCaneta.getSelectedRow(), 1);
        } else if (rb14.isSelected()) {
            modelo.setValueAt(Float.parseFloat(rb14.getText()), tbCaneta.getSelectedRow(), 1);
        } else {
            modelo.setValueAt(Float.parseFloat(rb16.getText()), tbCaneta.getSelectedRow(), 1);
        }
        
        if ( rbAzul.isSelected())
        {
            modelo.setValueAt(rbAzul.getText(),tbCaneta.getSelectedRow(), 2);
        } else if (rbVermelha.isSelected()) {
            modelo.setValueAt(rbVermelha.getText(),tbCaneta.getSelectedRow(), 2);
        } else if ( rbPreta.isSelected()) {
            modelo.setValueAt(rbPreta.getText(),tbCaneta.getSelectedRow(), 2);
        } else {
            modelo.setValueAt(rbVerde.getText(),tbCaneta.getSelectedRow(), 2);
        }
        modelo.setValueAt(nivelCarga.getText(), tbCaneta.getSelectedRow(), 3);
    }//GEN-LAST:event_btnEditarActionPerformed

    private void tamparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamparActionPerformed
        // TODO add your handling code here:
        int erro = caneta.tampar();
        
        if ( erro > 0 ) {
            JOptionPane.showMessageDialog(this,"A caneta JÁ está TAMPADA");
        }
    }//GEN-LAST:event_tamparActionPerformed

    private void destamparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destamparActionPerformed
        // TODO add your handling code here:
        int erro = caneta.destampar();
        if ( erro > 0 ) {
           JOptionPane.showMessageDialog(this,"A caneta JÁ está DESTAMPADA");
        }
    }//GEN-LAST:event_destamparActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        // TODO add your handling code here:
        nivelCarga.setText(String.valueOf(jSlider1.getValue()));
    }//GEN-LAST:event_jSlider1StateChanged

    private void rbVermelhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVermelhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVermelhaActionPerformed

    private void rb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb10ActionPerformed

    private void rb07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb07ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb07ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
       modelo.removeRow(tbCaneta.getSelectedRow());
       
    }//GEN-LAST:event_jButton3MouseClicked

    private void btnEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarMouseClicked
        // TODO add your handling code here:
        
        modelo.setValueAt(txtModelo.getText(),tbCaneta.getSelectedRow(), 0);
        
        if (rb07.isSelected()) {
            modelo.setValueAt(Float.parseFloat(rb07.getText()), tbCaneta.getSelectedRow(), 1);
        } else if (rb10.isSelected()) {
            modelo.setValueAt(Float.parseFloat(rb10.getText()), tbCaneta.getSelectedRow(), 1);
        } else if (rb14.isSelected()) {
            modelo.setValueAt(Float.parseFloat(rb14.getText()), tbCaneta.getSelectedRow(), 1);
        } else {
            modelo.setValueAt(Float.parseFloat(rb16.getText()), tbCaneta.getSelectedRow(), 1);
        }
        
        if ( rbAzul.isSelected())
        {
            modelo.setValueAt(rbAzul.getText(),tbCaneta.getSelectedRow(), 2);
        } else if (rbVermelha.isSelected()) {
            modelo.setValueAt(rbVermelha.getText(),tbCaneta.getSelectedRow(), 2);
        } else if ( rbPreta.isSelected()) {
            modelo.setValueAt(rbPreta.getText(),tbCaneta.getSelectedRow(), 2);
        } else {
            modelo.setValueAt(rbVerde.getText(),tbCaneta.getSelectedRow(), 2);
        }
        modelo.setValueAt(nivelCarga.getText(), tbCaneta.getSelectedRow(), 3);
        if(caneta.tampar() == 1) {
            modelo.setValueAt("Tampada", tbCaneta.getSelectedRow(), 4);
        } else {
            modelo.setValueAt("Destampada", tbCaneta.getSelectedRow(), 4);
        }
         
        
        /*
        modelo.setValueAt("Bic", 0, 0);
        modelo.setValueAt(tbCaneta.getSelectedRow(),0, 1);
        modelo.setValueAt(tbCaneta.getSelectedRow(),0, 2);
        modelo.setValueAt(tbCaneta.getSelectedRow(),0, 3);
       */
    }//GEN-LAST:event_btnEditarMouseClicked

    private void tbCanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbCanetaMouseClicked
        // TODO add your handling code here:
        String caneta_modelo = (String) modelo.getValueAt(tbCaneta.getSelectedRow(), 0);
        Float caneta_ponta = (Float) modelo.getValueAt(tbCaneta.getSelectedRow(), 1);
        String caneta_cor = (String) modelo.getValueAt(tbCaneta.getSelectedRow(), 2);
        Integer caneta_carga = (Integer) modelo.getValueAt(tbCaneta.getSelectedRow(), 3);

        txtModelo.setText(caneta_modelo);
        if (caneta_cor.equals("Azul")) {
            rbAzul.setSelected(true);
            rbVermelha.setSelected(false);
            rbPreta.setSelected(false);
            rbVerde.setSelected(false);
        } else if (caneta_cor.equals("Vermelha")) {
            rbVermelha.setSelected(true);
            rbAzul.setSelected(false);
            rbPreta.setSelected(false);
            rbVerde.setSelected(false);

        } else if(caneta_cor.equals("Preta")) {
            rbPreta.setSelected(true);
            rbAzul.setSelected(false);
            rbVermelha.setSelected(false);
            rbVerde.setSelected(false);
        } else {
            rbVerde.setSelected(true);
            rbAzul.setSelected(false);
            rbVermelha.setSelected(false);
            rbPreta.setSelected(false);

        }
        if (caneta_ponta.equals(0.7)) {
            rb07.setSelected(true);
            rb10.setSelected(false);
            rb14.setSelected(false);
            rb16.setSelected(false);
        } else if (caneta_ponta.equals(1.0)) {
            rb10.setSelected(true);
            rb07.setSelected(false);
            rb14.setSelected(false);
            rb16.setSelected(false);
        } else if (caneta_ponta.equals(1.4)) {
            rb14.setSelected(true);
            rb07.setSelected(false);
            rb10.setSelected(false);
            rb16.setSelected(false);
        } else {
            rb16.setSelected(true);
            rb07.setSelected(false);
            rb10.setSelected(false);
            rb14.setSelected(false);
        }

        nivelCarga.setText(caneta_carga.toString());
        jSlider1.setValue(caneta_carga);
    }//GEN-LAST:event_tbCanetaMouseClicked

    private void rbVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbVerdeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbVerdeActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        modelo.removeRow(tbCaneta.getSelectedRow());
    }//GEN-LAST:event_jButton4MouseClicked
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Cores;
    private javax.swing.ButtonGroup Pontas;
    private javax.swing.JButton btnEditar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cadastrarButtom;
    private javax.swing.JButton destampar;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel nivelCarga;
    private javax.swing.JRadioButton rb07;
    private javax.swing.JRadioButton rb10;
    private javax.swing.JRadioButton rb14;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JRadioButton rbAzul;
    private javax.swing.JRadioButton rbPreta;
    private javax.swing.JRadioButton rbVerde;
    private javax.swing.JRadioButton rbVermelha;
    private javax.swing.JButton tampar;
    private javax.swing.JTable tbCaneta;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
